#!/usr/bin/with-contenv bash

cd /app

if [ ! -f "package.json" ]; then
	echo "Error: package.json not found" >&2
	exit 1
fi

if [ "$NODE_ENV" != "production" ]; then
	echo "**** Installing dependencies... ****"

	s6-setuidgid abc pnpm install --frozen-lockfile --ignore-scripts --store-dir $PNPM_HOME/.store
fi
