#!/usr/bin/with-contenv bash

cd /app

echo "**** Starting app ****"

if [ "$MODE" != "production" ]; then
	exec s6-setuidgid abc pnpm run dev --host 0.0.0.0
else
	exec s6-setuidgid abc npm run start
fi
