---
name: Deploy

on:
  workflow_dispatch:
  push: &trigger
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - ".dockerignore"
      - "Dockerfile"
      - "components.json"
      - "index.html"
      - "package.json"
      - "pnpm-*.json"
      - "tsconfig*.json"
      - "vite.config.*"
      - "src/**"
      - "public/**"
      - "root/**"
  pull_request: *trigger
  release:
    types:
      - published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set Variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" != "release" ]; then
            echo "API_URL=${{ env.DEV_API_URL }}" >> $GITHUB_OUTPUT
            echo "LATEST=false" >> $GITHUB_OUTPUT
            echo "TAGS=dev" >> $GITHUB_OUTPUT
          else
            echo "API_URL=${{ env.API_URL }}" >> $GITHUB_OUTPUT
            echo "LATEST=true" >> $GITHUB_OUTPUT
            echo "TAGS<<EOF" >> $GITHUB_OUTPUT
            echo "type=semver,pattern={{version}}" >> $GITHUB_OUTPUT
            echo "type=semver,pattern={{major}}.{{minor}}" >> $GITHUB_OUTPUT
            echo "type=semver,pattern={{major}}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        uses: docker/metadata-action@v6
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: ${{ steps.vars.outputs.TAGS }}
          flavor: |
            latest=${{ steps.vars.outputs.LATEST }}
          labels: |
            maintainer=me@zuni.kim
            org.opencontainers.image.authors=me@zuni.kim
            org.opencontainers.image.vendor=Team Overclock
            org.opencontainers.image.title=Lifemap Frontend
            org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ steps.vars.outputs.LATEST == 'true' && 'prod' || 'dev' }}
          build-args: |
            VITE_API_URL=${{ steps.vars.outputs.API_URL }}
            VITE_BACKEND_URL=${{ steps.vars.outputs.API_URL }}
            VITE_KAKAO_MAP_API_KEY=${{ secrets.KAKAO_MAP_API_APP_KEY }}
            VITE_KAKAO_MAP_API_APP_KEY=${{ secrets.KAKAO_MAP_API_APP_KEY }}

          # pr에서는 테스트용이기 때문에 push하지 않음 (dry-run)
          push: ${{ github.event_name != 'pull_request' }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
